RentSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apprtrent.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='home'),
    path('', include('apprtrent.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apprtrent/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from apprtrent.views import Home, SignUPView, AddAppartment, AddAppartmentsPhoto, AppartmentsView, \
    AppartmentView, ChangeAppartment, AddOwner, AppartmentsEditList, DeleteAppartment, \
    UpdateArticleView, ArticleEditList, ArticleView

app_name = 'apprtrent'
urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': ''}, name="logout"),
    path('signup/', SignUPView.as_view(), name="signup"),

    path('add_appartment/', AddAppartment.as_view(), name="add-appartment"),
    path('update_appartment/<int:appartment_pk>', ChangeAppartment.as_view(), name="update-appartment"),
    path('delete_appartment/<int:appartment_pk>', DeleteAppartment.as_view(), name="delete-appartment"),
    path('appartment_edit_list/', AppartmentsEditList.as_view(), name="edit-list-appartment"),

    path('add_photo/<int:appartment_id>', AddAppartmentsPhoto.as_view(), name="add-photo"),
    path('add_owner/', AddOwner.as_view(), name="add-owner"),
    path('appartments/', AppartmentsView.as_view(), name="appartments"),
    path('appartments/<str:city>/', AppartmentsView.as_view(), name="appartments-by-city"),
    path('appartment/<int:appartment_id>', AppartmentView.as_view(), name="appartment"),
    path('appartment/<int:appartment_id>/<str:message>', AppartmentView.as_view(), name="appartment-message"),

    path('article/<int:pk>', ArticleView.as_view(), name='article' ),
    path('update_article/<int:article_pk>', UpdateArticleView.as_view(), name='update-article'),
    path('article_list/', ArticleEditList.as_view(), name='article-list'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apprtrent/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import date


DISTANCE = (
    (1, "w Centrum"),
    (2, "blisko"),
    (3, "szybki dojazd komunikacją miejską"),
    (4, "daleko od Centrum"),
)



class User(AbstractUser):
    class Meta:
        verbose_name = 'użytkownik'
        verbose_name_plural = 'użytkownicy'
        ordering = ['username']


class Owner(models.Model):
    first_name = models.CharField(max_length=30, verbose_name="Imię", blank=True)
    last_name = models.CharField(max_length=64, verbose_name="Nazwisko", blank=True)
    company_name = models.CharField(max_length=128, verbose_name="Nazwa firmy", blank=True)
    if_vat = models.BooleanField(default=True, verbose_name="płatnik VAT", help_text='Czy jest płatnikiem VAT')
    vat_number = models.CharField(max_length=10, blank=True, verbose_name="NIP")
    address_city = models.CharField(max_length=128, verbose_name="Miasto")
    address_code = models.CharField(max_length=6, help_text="00-000", verbose_name="kod")
    address_str = models.CharField(max_length=128, verbose_name="Ulica i nr")
    address_no = models.CharField(max_length=16, blank=True, verbose_name="nr lokalu")
    tel_no = models.CharField(max_length=32, verbose_name="Nr telefonu", blank=True)
    e_mail = models.EmailField(blank=True, verbose_name="Email")
    comment = models.TextField(blank=True, verbose_name="Dodatkowe informacje")

    class Meta:
        verbose_name = 'Właścicel'
        verbose_name_plural = 'Właściciele'

    def __str__(self):
        return f'{self.first_name} {self.last_name} {self.company_name}'


class City(models.Model):
    city_name = models.CharField(max_length=60, verbose_name="miasto")

    def __str__(self):
        return self.city_name

class Facility(models.Model):
    name = models.CharField(max_length=64, verbose_name="Udogodnienia/Wyposażenie")

    def __str__(self):
        return self.name

class Fee(models.Model):
    name = models.CharField(max_length=64, verbose_name="dodatkowa opłata")
    value = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.name



class Appartment(models.Model):
    app_name = models.CharField(max_length=128, verbose_name="Nazwa apartamentu")
    description = models.TextField(verbose_name="Opis apartamentu", blank=True)
    address_city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name="miasto")
    address_code = models.CharField(max_length=6, help_text="00-000", verbose_name="kod")
    address_str = models.CharField(max_length=128, verbose_name="Ulica i nr")
    address_no = models.CharField(max_length=16, blank=True, verbose_name="nr lokalu")
    area = models.SmallIntegerField(verbose_name="powierzchnia")
    floor = models.SmallIntegerField(verbose_name="piętro")
    no_of_rooms = models.SmallIntegerField(verbose_name="liczba pokoi")
    no_of_guests = models.SmallIntegerField(verbose_name="liczba osób")
    no_of_beds = models.SmallIntegerField(verbose_name="liczba łóżek")
    facilities = models.ManyToManyField(Facility, verbose_name="udogodnienia/wyposażenie")
    fees = models.ManyToManyField(Fee, verbose_name="dodatkowe opłaty")
    day_price = models.DecimalField(max_digits=6, default=200.00, decimal_places=2, verbose_name="Cena za dzień")
    special_weekly_price = models.DecimalField(max_digits=6, default=400.00, decimal_places=2, blank=True, null=True, verbose_name="Cena specjalna za tydzień wynajmu")
    deposit = models.SmallIntegerField(default=0, verbose_name="zwrotna kaucja")
    best_app = models.BooleanField(default=True, verbose_name="wyróżniony", help_text="czy apartament ma być pokazywany na stronie głównej")
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE, verbose_name="właściciel")
    distance = models.SmallIntegerField(choices=DISTANCE, verbose_name="odległość od Centrum")


    class Meta:
        ordering = ['address_city', 'app_name']
        permissions = (
            ("new_appartment", "Can add new appartment"),
            ("modify_appartment", "Can change appartment"),
            # ("delete_appartment", "Can delete appartment"),

            )

    def __str__(self):
        return self.app_name


def app_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/app_<id>/<filename>
    return 'app_{0}/{1}'.format(instance.appartment.id, filename)


class Photo(models.Model):
    # path = models.ImageField(max_length=128, upload_to="photos/", verbose_name="zdjęcie apartamentu")
    path = models.ImageField(max_length=128, upload_to=app_directory_path)
    appartment = models.ForeignKey(Appartment, on_delete=models.CASCADE)


class Booking(models.Model):
    checkin_date = models.DateField(default=date.today, blank=True, verbose_name="Rezerwacja od dnia")
    checkout_date = models.DateField(verbose_name="Rezerwacja do dnia")
    appartment = models.ForeignKey(Appartment, on_delete=models.CASCADE)
    email = models.EmailField()

    class Meta:
        unique_together = ('checkin_date', 'checkout_date', 'appartment')

    def __str__(self):
        return f'{self.appartment}, {self.checkin_date}, {self.checkout_date}'


class Article(models.Model):
    name = models.CharField(max_length=60, verbose_name="Nazwa")
    article_text = models.TextField(blank=True, verbose_name="Treść")

    def __str__(self):
        return self.name

apprtrent/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.checks import messages
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView
from datetime import date, datetime
from django.db import IntegrityError
from django.core.exceptions import PermissionDenied

from apprtrent.forms import AddAppartmentPhotoForm, UserCreationForm2, AddAppartmentForm, AddBookingForm, \
    SearchAppartmentsInCity
from apprtrent.models import Appartment, Photo, Facility, Owner, City, Booking, Article


# Home
class Home(View):

    def get(self, request):
        return render(request, 'apprtrent/home.html')


# Tworzenie nowego usera
class SignUPView(View):
    def get(self, request):
        form = UserCreationForm()
        return render(request, 'apprtrent/signup.html', {'form': form})

    def post(self, request):
        form = UserCreationForm2(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect(reverse('apprtrent:home'))
        return render(request, 'apprtrent/signup.html', {'form': form})


class ArticleView(DetailView):
    model = Article
    template_name = 'apprtrent/display_article.html'


class ArticleEditList(ListView):
    template_name = 'apprtrent/article_edit_list.html'

    def get_queryset(self):
        return Article.objects.all()


class UpdateArticleView(UpdateView):
    model = Article
    fields = '__all__'
    template_name_suffix = '_update_form'
    pk_url_kwarg = "article_pk"
    success_url = reverse_lazy('apprtrent:article-list')


# lista apartamentów do edycji
class AppartmentsEditList(View):
    def get(self, request):
        appartments = Appartment.objects.all().order_by("address_city")
        photos = Photo.objects.all()
        return render(request, "apprtrent/appartment_edit_list.html", {"appartments": appartments, "photos": photos})


# dodawanie apartamentu (z ograniczonymi uprawnieniami)
class AddAppartment(PermissionRequiredMixin, View):
    permission_required = 'apprtrent.new_appartment'

    def get(self, request):
        form = AddAppartmentForm()
        return render(request, "apprtrent/appartment_create_form.html", {"form": form})

    def post(self, request):
        form = AddAppartmentForm(request.POST)
        if form.is_valid():
            appartment = form.save()
            return redirect(reverse('apprtrent:add-photo', args=[appartment.id]))
        return render(request, "apprtrent/appartment_create_form.html", {"form": form})


# edycja i zmiana danych w apartamentcie
class ChangeAppartment(PermissionRequiredMixin, UpdateView):
    permission_required = 'apprtrent.change_appartment'

    model = Appartment
    fields = '__all__'
    template_name_suffix = '_update_form'
    pk_url_kwarg = 'appartment_pk'
    success_url = reverse_lazy('apprtrent:edit-list-appartment')


# usuwanie apartamentu
class DeleteAppartment(PermissionRequiredMixin, DeleteView):
    permission_required = 'apprtrent.delete_appartment'

    model = Appartment
    pk_url_kwarg = 'appartment_pk'
    success_url = reverse_lazy('apprtrent:edit-list-appartment')


# dodawanie właściciela
class AddOwner(PermissionRequiredMixin, CreateView):
    permission_required = 'apprtrent.add_owner'

    model = Owner
    fields = '__all__'
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('apprtrent:home')


# dodawanie zdjęć do apartamentu
class AddAppartmentsPhoto(View):

    def get(self, request, appartment_id):
        appartment = Appartment.objects.get(pk=appartment_id)
        photos = appartment.photo_set.all()
        form = AddAppartmentPhotoForm(instance=appartment)

        return render(request, "apprtrent/add_photos_form.html",
                      {"form": form, "appartment": appartment, "photos": photos, "button": "Dodaj zdjęcie"})

    def post(self, request, appartment_id):
        appartment = Appartment.objects.get(pk=appartment_id)
        form = AddAppartmentPhotoForm(request.POST, request.FILES)
        if form.is_valid():
            photo = form.save(commit=False)
            photo.appartment = appartment
            if request.user.has_perm('apprtrent.can_add_photo'):
                photo.save()
            else:
                raise PermissionDenied("Access denied")
            return redirect(reverse('apprtrent:add-photo', kwargs={'appartment_id': photo.appartment_id}))
        return render(request, "apprtrent/add_photos_form.html", {"form": form, "button": "Dodaj zdjęcie"})


# pokazuje apartamenty na stronie głównej, wszystkie lub w danym mieście
class AppartmentsView(View):
    def get(self, request, city=None):
        if city:
            city = City.objects.get(city_name=city)
            appartments = Appartment.objects.filter(address_city=city)
        else:
            appartments = Appartment.objects.all()
        cities = City.objects.all()
        photos = Photo.objects.all()
        form = SearchAppartmentsInCity()
        return render(request, "apprtrent/display.html", {"appartments": appartments, "form": form,
                                                          "cities": cities, "photos": photos})

    def post(self, request, city=None):
        form = SearchAppartmentsInCity(request.POST)
        appartments = Appartment.objects.all()
        cities = City.objects.all()
        photos = Photo.objects.all()
        if form.is_valid():
            city = form.cleaned_data['address_city']
            return redirect(reverse('apprtrent:appartments-by-city', kwargs={'city': city}))
        return render(request, "apprtrent/display.html", {"appartments": appartments, "form": form,
                                                          "cities": cities, "photos": photos})


# pokazuje wybrany apartament z możliwością jego rezerwacji
class AppartmentView(View):
    def get(self, request, appartment_id, message=None):
        if message:
            message = message
        appartment = get_object_or_404(Appartment, pk=appartment_id)
        facilities = appartment.facilities.all()
        fees = appartment.fees.all()
        photos = appartment.photo_set.all()
        today = date.today()
        booked_already = appartment.booking_set.filter(checkout_date__gt=date.today()).order_by("checkin_date")
        first_booked = today
        if booked_already:
            for b in booked_already:
                checkin_date = b.checkin_date
                checkout_date = b.checkout_date
                if checkout_date - (checkout_date - checkin_date) <= first_booked:
                    first_booked = checkout_date
        form = AddBookingForm(instance=appartment, initial={"checkin_date": first_booked})
        return render(request, "apprtrent/display_one.html", {"message": message, "appartment": appartment,
                                                              "facilities": facilities, "fees": fees, "photos": photos,
                                                              "booked_already": booked_already,
                                                              "today": today, "form": form})

    def post(self, request, appartment_id, message=None):
        appartment = Appartment.objects.get(pk=appartment_id)
        today = datetime.today().date()
        form = AddBookingForm(request.POST)
        if form.is_valid():
            booking = form.save(commit=False)
            booking.appartment = appartment
            booked_already_after_checkin = appartment.booking_set.filter(checkout_date__gt=booking.checkin_date)
            checkin_date = booking.checkin_date
            checkout_date = booking.checkout_date
            if checkin_date < today:
                message = f'Rezerwacje wstecz nie są możliwe. Wybierz wolny termin po {today}'
                return redirect(reverse('apprtrent:appartment-message',
                                        kwargs={'appartment_id': appartment_id, 'message': message}))

            #  sprawdza czy temrmin jest już zajęty, jeżeli są jakieś rezerwacje po dacie check_in
            if booked_already_after_checkin:
                for b in booked_already_after_checkin:
                    date_in = b.checkin_date
                    date_out = b.checkout_date
                    if checkin_date <= date_in and checkout_date > date_in and checkout_date < date_out or \
                            checkin_date >= date_in and checkout_date <= date_out or \
                            checkin_date >= date_in and checkin_date <= date_out or \
                            checkin_date <= date_in and checkout_date >= date_out:
                        message = "Ten termin został już zarezerwowany"
                        return redirect(reverse('apprtrent:appartment-message',
                                                kwargs={'appartment_id': appartment_id, 'message': message}))
            try:
                booking.save()
            except IntegrityError:
                message = "Ten termin jest już zarezerwowany"
                return redirect(reverse('apprtrent:appartment-message',
                                        kwargs={'appartment_id': appartment_id, 'message': message}))

            message = "Dokonano wstępnej rezerwacji, dziękujemy"
            return redirect(
                reverse('apprtrent:appartment-message', kwargs={'appartment_id': appartment_id, 'message': message}))

apprtrent/templates/apprtrent/appartment_confirm_delete.html
{% extends "apprtrent/base.html" %}

{% block content %}

    <div class="container"><p></p>

        <nav class="navbar navbar-light bg-light">

            <form action="" method="post">
                {% csrf_token %}
                <span>Usunąć apartament?</span>

                        <input type="hidden" value="{{ object.id }}" name="itemsToDelete" />
                        <h3>{{ object.app_name }}</h3>
                <input type="submit" class="btn btn-danger btn-sm" value="Ok" name="confirm_delete" />
            <a class="btn btn-primary btn-sm" href="{% url 'apprtrent:edit-list-appartment' %}" role="button">Anuluj</a>
            </form>
        </nav>
    </div>
    <hr>

{% endblock %}

apprtrent/templates/apprtrent/article_edit_list.html
{% extends "apprtrent/base.html" %}

{% block content %}

    <div class="container">
        <h3 class="info-title"> Lista artykułów na stronach:</h3>
            {% for article in object_list %}
                <table class="table table-striped">
                    <tr>
                        <td width=70%><a href="{% url 'apprtrent:article' article.pk %}">{{ article.name }}</a></td>
                        <td width=10%><a class="btn btn-primary btn-sm" href="{% url 'apprtrent:update-article' article.pk %}" role="button">Edytuj</a></td>
        {#                <td width=10%><a class="btn btn-danger btn-sm" href="{% url 'apprtrent:delete-article' art.pk %}" role="button">Usuń</a></td>#}
                    </tr>
                </table>
            {% endfor %}
    </div>
    <hr>

{% endblock %}

apprtrent/templates/apprtrent/base.html
<!doctype html>

{% load static %}

<html>
    <head><meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <title>
        {% block title %}Wynajem apartamentów{% endblock %}
    </title>
    </head>

    <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark"><a class="navbar-brand" href="{% url 'apprtrent:home' %}">RentLab</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

            {% include "apprtrent/menu.html" %}
            {% if request.user.is_authenticated %}
            {% include "apprtrent/menu_manage.html" %}
            {% endif %}


            {% if request.user.is_authenticated %} <span class="text-warning"><small>Zalogowany: {{ request.user }} |
                <a href="{% url 'apprtrent:logout' %}"> Wyloguj się</a>
            {% else %}
                <a href="{% url 'apprtrent:login' %}">Logowanie</a> / <a href="{% url 'apprtrent:signup' %}">Rejestracja</a>
            {% endif %}
            </small></span>

    </nav>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important:
                    {% endif %}
                    {{ message }}
                </li>
                {% endfor %}
            </ul>
            {% endif %}


        {% block content %}
        {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

apprtrent/templates/apprtrent/display.html
{% extends "apprtrent/base.html" %}
{% block content %}

    <div class="container">

        <div class="select2-container">
                <div class="d-flex bd-highlight mb-3">
                  <div class="ml-auto p-2 bd-highlight">
                    <form method="POST" action="">
                        {% csrf_token %}
                        {{ form }} <button class="btn btn-primary btn-sm" type="submit" role="button" value="Ok">Szukaj</button>
                    </form>
                  </div>
                </div>
        </div>
        <nav class="navbar">
            <ul class="list-unstyled">

                {% for app in appartments %}

                <li class="media pr-3 mb-2" style="background-color: aliceblue"><a href="{{ app.photo_set.first.path.url }}">
                    <img class="mr-3 mb-0" style="width: 250px" src="{{ app.photo_set.first.path.url }}" alt="Generic placeholder image"></a>

                    <div class="media-body mt-1">
                        <a class="app-description" href="{% url 'apprtrent:appartment' app.pk %}"><h4 class="media-heading">{{ app.app_name }}</h4></a>
                        <h5 class="mt-0 app-description">{{ app.address_str }}, {{ app.address_city }}</h5>
                        <span class="app-description"> {{ app.description }}</span>
                        <p></p>
                        <span style="color: dimgrey"><small>
                        <table class="table table-bordered">
                            <tbody>
                                <tr class="text-center">
                                  <td>lokalizacja: {{ app.get_distance_display }}</td>
                                  <td>max osób: {{ app.no_of_guests }}</td>
                                  <td>łóżek: {{ app.no_of_beds }}</td>
                                  <td>pow.: {{ app.area }}mkw</td>
                                  <td>piętro: {{ app.floor }}</td>
                                  <td>pokoi: {{ app.no_of_rooms }}</td>
                                  <td>depozyt: {{ app.deposit }}</td>
                                </tr>
                            </tbody>
                        </table>
                        </small></span>
                    </div>
                </li>

                {% endfor %}

            </ul>


            <hr>


        </nav>

    </div>

{% endblock %}

apprtrent/templates/apprtrent/display_article.html
{% extends "apprtrent/base.html" %}
{% block content %}

    <div class="bg">
        <div class="container">
            <h5 class="info-home">{{ article.name|title }}</h5>
            <hr>

            <div class="row show-grid">
                <div class="col-md-7 text-article">{{ article.article_text }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

apprtrent/templates/apprtrent/display_one.html
{% extends "apprtrent/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="container p-3 appartment-info">
                <div class="container p-3 mt-2 mb-2 bg-dark text-light"><h3>Rezerwacja apartamentu</h3>

                    <div class="row">
                        <div class="col-4">

                            <form method="POST" action="" class="form">
                                {% csrf_token %}
                                <span class="text-danger">
                                    {% if message %}
                                        <small>{{ message }}</small>
                                    {% endif %}
                                </span>

                                {{ form|crispy }}

                                <button class="btn btn-primary btn-sm" type="submit" role="button" value="Ok">Rezerwuj</button>
                                <a class="btn btn-primary btn-sm" href="{% url 'apprtrent:appartments' %}" role="button">Anuluj</a>
                            </form></div>

                    <div class="col-2"></div>

                    <div class="col"> Zarezerwowane dni:<br>
                        {% if booked_already %}
                            {% for b in booked_already %}
                            {{ b.checkin_date }} - {{ b.checkout_date }}<br>
                        {% endfor %}
                        {% else %} Ten apartament nie ma jeszcze żadnych rezerwacji.
                        {% endif %}</div>

                    </div>
                  </div>


            <nav class="navbar">
                <div class="container">
                    <div class="row">
                        <div class="col"><span class="navbar-text">
                            <h3 class="text-body"> {{ appartment.app_name }}</h3>
                            <h5 class="text-body">ul. {{ appartment.address_str }}, {{ appartment.address_city }}</h5>
                        </span>
                        </div>
                    </div>
                </div>

               <span><small>
                    <table class="table table-bordered">
                        <tbody>
                            <tr class="text-body text-center">
                              <td>lokalizacja: {{ appartment.get_distance_display }}</td>
                              <td>max osób: {{ appartment.no_of_guests }}</td>
                              <td>łóżek: {{ appartment.no_of_beds }}</td>
                              <td>pow.: {{ appartment.area }}mkw</td>
                              <td>piętro: {{ appartment.floor }}</td>
                              <td>pokoi: {{ appartment.no_of_rooms }}</td>
                              <td>depozyt: {{ appartment.deposit }}</td>
                            </tr>
                        </tbody>
                    </table>
                </small></span>
                <div class="container">
                <h6 class="cena">Cena od: <span>{{ appartment.day_price }} PLN/dzień</span></h6>
                </div>
            </nav>

            <div class="container">
                {% include "apprtrent/display_photos.html" %}
            </div>

            <div class="container app-description"> {{ appartment.description }}</div>

            <div class="container">
                <span><small>
                {% for fac in facilities %}
                     <ul class="list-group list-group-flush">
                        <li class="list-group-item" style="background-color: aliceblue">{{ fac.name }}</li>
                    </ul>
                {% endfor %}<br>
                </small></span>
            </div>

    </div>


{% endblock %}

apprtrent/templates/apprtrent/menu_manage.html
<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Zarządzanie danymi
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'apprtrent:add-appartment' %}">Dodaj apartament</a>
          <a class="dropdown-item" href="{% url 'apprtrent:add-owner' %}">Dodaj właściciela</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{%  url 'apprtrent:edit-list-appartment' %}">Lista apartamentów</a></a>
        </div>
      </li>
    </ul>

        <ul class="navbar-nav">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Zarządzanie treścią
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'apprtrent:article-list' %}">Edytuj treści</a>
        </div>
      </li>
    </ul>
 </div>